// GENERATED by tools/gen_tokens.py from tokens.json — do not edit by hand.
// Source of truth: design/sam-tokens.css

import 'dart:ui';

/// Raw design tokens. Screens never read these directly — they go through
/// AppColors / AppTypography so a theme switch reaches every widget.
class Tokens {
  const Tokens._();

  // ---- spacing ----
  static const double spaceLg = 16.0;
  static const double spaceMd = 12.0;
  static const double spaceSm = 8.0;
  static const double spaceXl = 20.0;
  static const double spaceXs = 4.0;
  static const double spaceXxl = 24.0;
  static const double spaceXxxl = 32.0;
  static const double screenH = 20.0;
  static const double sectionGap = 20.0;

  // ---- radii ----
  static const double rLg = 20.0;
  static const double rMd = 14.0;
  static const double rPill = 50.0;
  static const double rSm = 10.0;

  // ---- font sizes ----
  static const double fs2xs = 9.0;
  static const double fsXxs = 10.0;
  static const double fsXs = 11.0;
  static const double fsSm = 12.0;
  static const double fsSub = 13.0;
  static const double fsMd = 14.0;
  static const double fsCallout = 15.0;
  static const double fsLg = 16.0;
  static const double fsHeadline = 17.0;
  static const double fsSubtitle = 18.0;
  static const double fsXl = 20.0;
  static const double fsXxl = 22.0;
  static const double fsTitle = 28.0;
  static const double fsHero = 34.0;
  static const double fsMega = 48.0;
  static const double fsCountdown = 52.0;
  static const double fsDisplay = 56.0;

  // ---- line heights (multipliers) ----
  static const double lhNormal = 1.45;
  static const double lhRelaxed = 1.5;
  static const double lhSnug = 1.28;
  static const double lhTight = 1.12;

  // ---- shared hues (same in both themes) ----
  static const Color brand = Color(0xFF7C3AED);
  static const Color brandSoft = Color(0xFFB098FB);
  static const Color brandDeep = Color(0xFF6D35C8);
  static const Color accentCyan = Color(0xFF5BC8E6);
  static const Color success = Color(0xFF34D399);
  static const Color successStrong = Color(0xFF10BE84);
  static const Color warning = Color(0xFFFFB74D);
  static const Color danger = Color(0xFFEF4444);
  static const Color info = Color(0xFF8B95D6);
  static const Color mood = Color(0xFF4DD0E1);
  static const Color energy = Color(0xFF81C784);
  static const Color sleep = Color(0xFF9FA8DA);
  static const Color onBrand = Color(0xFFFFFFFF);
  static const Color tabSelected = Color(0xFF6D35C8);
}

/// Per-theme colour values.
class DarkTokens {
  const DarkTokens._();
  static const Color bg = Color(0xFF0A0A0F);
  static const Color bgDeep = Color(0xFF080511);
  static const Color surface = Color(0xFF1C1C24);
  static const Color surfaceTinted = Color(0xFF151519);
  static const Color elevated = Color(0xFF24242E);
  static const Color surface3 = Color(0xFF2A2A36);
  static const Color surfaceCard = Color(0xFF1E1E28);
  static const Color surfaceControl = Color(0xFF1A1B22);
  static const Color surfaceInk = Color(0xFF121216);
  static const Color border = Color(0xFF252530);
  static const Color borderSubtle = Color(0xFF1A1B22);
  static const Color hairline = Color(0x14FFFFFF);
  static const Color hairlineSoft = Color(0x0FFFFFFF);
  static const Color text = Color(0xFFFFFFFF);
  static const Color textSecondary = Color(0xC7FFFFFF);
  static const Color textMuted = Color(0x94FFFFFF);
  static const Color textDisabled = Color(0x61FFFFFF);
  static const Color brandContainer = Color(0xFF1A1530);
  static const Color successContainer = Color(0xFF1B2D1B);
  static const Color dangerContainer = Color(0xFF2D1B1B);
  static const Color dangerSoft = Color(0xFFEEA3A3);
  static const Color dangerStripe = Color(0xFFDC2626);
  static const Color glassTint = Color(0x0EFFFFFF);
  static const Color glassStroke = Color(0x24FFFFFF);
  static const Color tabBg = Color(0xB80A0A0F);
  static const Color tabUnselected = Color(0x59FFFFFF);
  static const Color ctaBorder = Color(0x3DB098FB);
  static const Color onSuccess = Color(0xFF0A0A0F);
  static const Color infoTint = Color(0x248B95D6);
  static const Color warningTint = Color(0x1FFFB74D);
  static const Color warningRow = Color(0x0FFFB74D);
}

class LightTokens {
  const LightTokens._();
  static const Color bg = Color(0xFFFFFFFF);
  static const Color bgDeep = Color(0xFFF5F7FA);
  static const Color surface = Color(0xFFF0F4F8);
  static const Color surfaceTinted = Color(0xFFEDE7FF);
  static const Color elevated = Color(0xFFE8ECF2);
  static const Color surface3 = Color(0xFFE0E4EC);
  static const Color surfaceCard = Color(0xFFF0F4F8);
  static const Color surfaceControl = Color(0xFFE8ECF2);
  static const Color surfaceInk = Color(0xFFF5F7FA);
  static const Color border = Color(0xFFD8DEE8);
  static const Color borderSubtle = Color(0xFFE3E8F0);
  static const Color hairline = Color(0x14000000);
  static const Color hairlineSoft = Color(0x0F000000);
  static const Color text = Color(0xFF111827);
  static const Color textSecondary = Color(0xFF374151);
  static const Color textMuted = Color(0xFF4B5563);
  static const Color textDisabled = Color(0xFF64748B);
  static const Color brandContainer = Color(0xFFEDE7FF);
  static const Color successContainer = Color(0xFFEAF8F0);
  static const Color dangerContainer = Color(0xFFFDECEC);
  static const Color dangerSoft = Color(0xFFB91C1C);
  static const Color dangerStripe = Color(0xFFDC2626);
  static const Color glassTint = Color(0x0A000000);
  static const Color glassStroke = Color(0x1A000000);
  static const Color tabBg = Color(0xEBFFFFFF);
  static const Color tabUnselected = Color(0x61111827);
  static const Color ctaBorder = Color(0x336D35C8);
  static const Color onSuccess = Color(0xFFFFFFFF);
  static const Color infoTint = Color(0x1A6D35C8);
  static const Color warningTint = Color(0x33FFB74D);
  static const Color warningRow = Color(0x1AFFB74D);
}
