#!/usr/bin/env python3
"""Generate core/design Color tokens from tokens.json.

tokens.json is exported from design/sam-tokens.css, so the Kotlin values are a
transcription rather than a second hand-typed copy that drifts.

    python3 tools/gen_theme.py
"""
import json, re, pathlib

ROOT = pathlib.Path(__file__).resolve().parent.parent
T = json.load(open(ROOT / 'tokens.json'))

def camel(name):
    head, *rest = name.split('-')
    return head + ''.join(p[:1].upper() + p[1:] for p in rest)

def argb(v):
    v = v.strip()
    if v.startswith('#'):
        h = v[1:]
        if len(h) == 3:
            h = ''.join(c * 2 for c in h)
        return f'0xFF{h.upper()}'
    m = re.match(r'rgba?\(\s*([\d.]+)[,\s]+([\d.]+)[,\s]+([\d.]+)(?:[,/\s]+([\d.]+))?\s*\)', v)
    if not m:
        raise ValueError('not a colour: ' + v)
    r, g, b = (int(float(m.group(i))) for i in (1, 2, 3))
    a = float(m.group(4)) if m.group(4) else 1.0
    return f'0x{int(round(a * 255)):02X}{r:02X}{g:02X}{b:02X}'

is_col = lambda v: v.startswith('#') or v.startswith('rgba')
per_theme = [k for k, v in T['dark'].items() if is_col(v)]
shared = [k for k, v in T['structure'].items() if is_col(v)]

L = ['// GENERATED by tools/gen_theme.py from tokens.json — do not edit by hand.',
     '// Source of truth: design/sam-tokens.css',
     '',
     'package com.steadyline.core.design',
     '',
     'import androidx.compose.ui.graphics.Color',
     '',
     '/** Hues that are identical in both themes. */',
     'internal object SharedHues {']
for k in shared:
    L.append(f'    val {camel(k)} = Color({argb(T["structure"][k])})')
L += ['}', '']

for theme in ('dark', 'light'):
    L.append(f'internal object {theme.capitalize()}Palette {{')
    for k in per_theme:
        L.append(f'    val {camel(k)} = Color({argb(T[theme][k])})')
    L += ['}', '']

out = ROOT / 'android/core/design/src/main/kotlin/com/steadyline/core/design/Palette.kt'
out.parent.mkdir(parents=True, exist_ok=True)
out.write_text('\n'.join(L))
print(f'wrote {out.relative_to(ROOT)}  ({len(shared)} shared, {len(per_theme)} per theme)')
