#!/usr/bin/env python3
"""Generate lib/theme/tokens.dart from tokens.json.

The Dart tokens must be a transcription of design/sam-tokens.css, not a
re-entry of the same values by hand. Re-run after changing the CSS:

    python3 tools/gen_tokens.py
"""
import json, re, sys, pathlib

ROOT = pathlib.Path(__file__).resolve().parent.parent
T = json.load(open(ROOT / 'tokens.json'))

def camel(name):
    head, *rest = name.split('-')
    return head + ''.join(p[:1].upper() + p[1:] for p in rest)

def to_color(v):
    v = v.strip()
    if v.startswith('#'):
        h = v[1:]
        if len(h) == 3:
            h = ''.join(c * 2 for c in h)
        return f'Color(0xFF{h.upper()})'
    m = re.match(r'rgba?\(\s*([\d.]+)[,\s]+([\d.]+)[,\s]+([\d.]+)(?:[,/\s]+([\d.]+))?\s*\)', v)
    if m:
        r, g, b = (int(float(m.group(i))) for i in (1, 2, 3))
        a = float(m.group(4)) if m.group(4) else 1.0
        return f'Color(0x{int(round(a*255)):02X}{r:02X}{g:02X}{b:02X})'
    raise ValueError('not a colour: ' + v)

def px(v):
    return float(v.replace('px', '').strip())

def num(v):
    return float(v.strip())

COLOR_KEYS = [k for k, v in T['dark'].items() if v.startswith('#') or v.startswith('rgba')]
# brand/semantic hues live in :root and are shared by both themes
SHARED_COLORS = [k for k, v in T['structure'].items()
                 if v.startswith('#') or v.startswith('rgba')]

L = []
w = L.append
w('// GENERATED by tools/gen_tokens.py from tokens.json — do not edit by hand.')
w('// Source of truth: design/sam-tokens.css')
w('')
w("import 'dart:ui';")
w('')
w('/// Raw design tokens. Screens never read these directly — they go through')
w('/// AppColors / AppTypography so a theme switch reaches every widget.')
w('class Tokens {')
w('  const Tokens._();')
w('')
w('  // ---- spacing ----')
for k in sorted(k for k in T['structure'] if k.startswith('space-')):
    w(f'  static const double {camel(k)} = {px(T["structure"][k])};')
w(f'  static const double screenH = {px(T["structure"]["screen-h"])};')
w(f'  static const double sectionGap = {px(T["structure"]["section-gap"])};')
w('')
w('  // ---- radii ----')
for k in sorted(k for k in T['structure'] if k.startswith('r-')):
    w(f'  static const double {camel(k)} = {px(T["structure"][k])};')
w('')
w('  // ---- font sizes ----')
for k in sorted((k for k in T['structure'] if k.startswith('fs-')),
                key=lambda k: px(T['structure'][k])):
    w(f'  static const double {camel(k)} = {px(T["structure"][k])};')
w('')
w('  // ---- line heights (multipliers) ----')
for k in sorted(k for k in T['structure'] if k.startswith('lh-')):
    w(f'  static const double {camel(k)} = {num(T["structure"][k])};')
w('')
w('  // ---- shared hues (same in both themes) ----')
for k in SHARED_COLORS:
    w(f'  static const Color {camel(k)} = {to_color(T["structure"][k])};')
w('}')
w('')
w('/// Per-theme colour values.')
for theme in ('dark', 'light'):
    w(f'class {theme.capitalize()}Tokens {{')
    w(f'  const {theme.capitalize()}Tokens._();')
    for k in COLOR_KEYS:
        w(f'  static const Color {camel(k)} = {to_color(T[theme][k])};')
    w('}')
    w('')

out = ROOT / 'flutter_app/lib/theme/tokens.dart'
out.write_text('\n'.join(L))
print(f'wrote {out.relative_to(ROOT)}')
print(f'  shared hues : {len(SHARED_COLORS)}')
print(f'  per-theme   : {len(COLOR_KEYS)} x2')
print(f'  lines       : {len(L)}')
